#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Dec 09, 2024 09:23:30 PM CST  platform: Windows NT
import configparser
import functools
import json
import logging
import sys
import tkinter as tk
import traceback
from time import sleep
from tkinter import filedialog, messagebox
from tkinter.constants import *

import requests
from openai.types.chat import ChatCompletionUserMessageParam

from cyf.project.client import client

_debug = True # False to eliminate debug printing from callback functions.
conf = configparser.ConfigParser()
conf.read('conf/conf.ini')
upload_prefix = conf["common"]["upload_pre"]
chat_suf = conf["common"]["chat_suf"]
model_list = [model_name for model_name in conf['model']]
server_list = [server_name + "|" + conf['server'][server_name] for server_name in conf['server']]
# 待上传文件地址
file_path = ""
# 暂存服务端回传的会话dict，用于构造对话dialog
dialogs = []



def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = client.Toplevel1(_top1)
    # 下拉框初始化
    _w1.serverCombobox.configure(values=server_list)
    _w1.modelCombobox.configure(values=model_list)
    root.mainloop()

def catch_exceptions(func):
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except Exception as e:
            traceback.print_exc()
            show_err(f"{e}")
    return wrapper

@catch_exceptions
def upload_file():
    print('talker_support.upload_file')
    global file_path, _w1, host
    file_path = filedialog.askopenfilename()
    if not file_path:
        return
    print(f"已选择文件: {file_path}")
    _w1.speakBox.configure(state="disabled")
    host = _w1.server_select.get()
    # api执行上传，
    with open(file_path, 'rb') as file:
        files = {'file': file}
        response = requests.post( f"http://{host}{upload_prefix}", files=files)
    if response.status_code == 200:
        url_suffix = response.text
        url = f"http://{host}{url_suffix}"
    else:
        print(response)
        show_err("上传失败，爬爬爬")
        return
    _w1.speakBox.configure(state="normal")
    # 输入框头部插入url
    _w1.speakBox.insert("1.0", url + " ")
    messagebox.showinfo("ojbk", f"您的文件已上传:{file_path}, url:{url}, 注意保密哦")

@catch_exceptions
def send_chat_pre():
    global root
    send_content = _w1.speakBox.get("1.0", END)
    _w1.result_text.insert(END, "提问：" + send_content + "\n")
    root.after(1, send_chat, send_content)

@catch_exceptions
def send_chat(send):
    # 接口内容组织&请求&返回
    global _w1, host
    print(f"model: {_w1.model_select.get()}, server:{_w1.server_select.get()}, user:{_w1.user_name.get()}")
    print(f"send chat content: {send}")
    # dialogs历史上下文，加上本次的user chat
    send = _w1.speakBox.get("1.0", END)
    dialogs.append(ChatCompletionUserMessageParam(role="user", content=send))
    host = _w1.server_select.get().split("|")[1]
    data = {
        "user": _w1.user_name.get(),
        "model": _w1.model_select.get(),
        "dialog": send
    }
    response = requests.post(f"http://{host}{chat_suf}", data)
    print(response)
    # 结果序列化存到dialog中
    dialogs.append(json.loads(response.text))
    _w1.result_text.insert(END, "回答：" + dialogs[-1]["content"] + "\n")
    return

def show_err(user_err: str):
    messagebox.showerror("有问题", f"报了个错: {user_err}")


if __name__ == '__main__':
    client.start_up()




