#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Dec 09, 2024 09:23:30 PM CST  platform: Windows NT

import sys
import tkinter as tk
from time import sleep
from tkinter import filedialog, messagebox

from cyf.project.client import client

_debug = True # False to eliminate debug printing from callback functions.
# 待上传文件地址
file_path = ""

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = client.Toplevel1(_top1)
    root.mainloop()

def upload_file():
    if _debug:
        print('talker_support.upload_file')
        global file_path, _w1
        file_path = filedialog.askopenfilename()
        if not file_path:
            return
        print(f"已选择文件: {file_path}")
        _w1.speakBox.configure(state="disabled")
        # 模拟执行上传，
        sleep(1)
        _w1.speakBox.configure(state="normal")
        url = f"http://url.url/{file_path}"
        _w1.speakBox.insert("1.0", f"http://url.url/{file_path}" + " ")
        msg = f"您的文件已上传:{file_path}, url:{url}, 注意保密哦"
        messagebox.showinfo("ojbk", msg)

def show_err(user_err: str):
    messagebox.showerror("有问题", f"报了个错: {user_err}")


if __name__ == '__main__':
    client.start_up()




