#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Dec 09, 2024 09:19:59 PM CST  platform: Windows NT

import os.path
import tkinter as tk
import tkinter.ttk as ttk
from tkinter import RIGHT, Y

import customtkinter
from click import style
from customtkinter import CTkTextbox, ThemeManager

_location = os.path.dirname(__file__)

import client_support

_bgcolor = 'gray82'
_fgcolor = 'black'


class Toplevel1:
    def __init__(self, top=None, title=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("1200x450+980+330")
        top.minsize(120, 1)
        top.maxsize(2564, 1421)
        top.resizable(1,  1)
        top.title(title)
        self.label_font = customtkinter.CTkFont(family="Microsoft YaHei", size=11, weight="bold")
        self.title_font = customtkinter.CTkFont(family="Microsoft YaHei", size=14, weight="bold")
        self.input_font = customtkinter.CTkFont(family="Microsoft YaHei", size=11, weight="bold")
        self.dialog_font = customtkinter.CTkFont(family="SimHei", size=12)

        self.top = top
        self.user_name = tk.StringVar()
        self.server_select = tk.StringVar()
        self.model_select = tk.StringVar()
        self.model_select.trace_add("write", client_support.switch_model_func)

        self.TSizegrip1 = ttk.Sizegrip(self.top)
        self.TSizegrip1.place(anchor='se', relx=5.0, rely=5.0)
        self.TSizegrip1.configure(style="TFrame")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg='#dcdad5',fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.TFrame1 = customtkinter.CTkFrame(self.top)
        self.TFrame1.place(relx=0.033, rely=0.022, relheight=0.967, relwidth=0.185)
        self.TFrame1.configure(border_width=1)

        self.userTag = customtkinter.CTkLabel(self.TFrame1, height=22, width=100, text='''用户名：''', font=self.label_font)
        self.userTag.place(relx=0.1, rely=0.029)
        self.userTag.configure(anchor='sw')
        self.userTag_tooltip = ToolTip(self.userTag, '''请填写自己的用户名''')

        self.userEntry = customtkinter.CTkEntry(self.TFrame1,  height=22, width=100, font=self.input_font)
        self.userEntry.place(relx=0.094, rely=0.089)
        self.userEntry.configure(cursor="ibeam")
        self.userEntry.configure(textvariable=self.user_name)

        self.serverTag = customtkinter.CTkLabel(self.TFrame1, height=22, width=100, text='''选择服务器：''', font=self.label_font)
        self.serverTag.place(relx=0.1, rely=0.138)
        self.serverTag.configure(anchor='sw')
        self.serverTag_tooltip = ToolTip(self.serverTag, '''本地测试没事别选''')

        self.serverCombobox = customtkinter.CTkComboBox(self.TFrame1, font=self.label_font, dropdown_font=self.label_font, variable=self.server_select, state="readonly")
        self.serverCombobox.place(relx=0.1, rely=0.207, relheight=0.053, relwidth=0.822)

        self.modelCombobox = customtkinter.CTkComboBox(self.TFrame1, font=self.label_font,
                                                       dropdown_font=self.label_font, variable=self.model_select, state="readonly")
        self.modelCombobox.place(relx=0.1, rely=0.345, relheight=0.053, relwidth=0.822)

        self.modelTag = customtkinter.CTkLabel(self.TFrame1, height=22, width=100, text='''选择模型(仅*-all模型支持文件类功能)：''', font=self.label_font)
        self.modelTag.place(relx=0.1, rely=0.276)
        self.serverTag.configure(anchor='sw')
        self.modelTag_tooltip = ToolTip(self.modelTag, '''默认使用gpt4o-mini''')

        self.TLabel_Title = customtkinter.CTkLabel(self.TFrame1, height=31, width=100, font=self.title_font)
        self.TLabel_Title.place(relx=0.1, rely=0.51)
        self.TLabel_Title.configure(wraplength=100)
        self.TLabel_Title.configure(text='''使用说明：''')
        self.TLabel_Title.configure(anchor='sw')

        self.TLabel_Content1 = customtkinter.CTkLabel(self.TFrame1, height=31, width=189, font=self.label_font)
        self.TLabel_Content1.place(relx=0.074, rely=0.59)
        self.TLabel_Content1.configure(text='''1.输入用户名,选择服务器与模型''')
        self.TLabel_Content1.configure(anchor='sw')

        self.TLabel_Content2 = customtkinter.CTkLabel(self.TFrame1, height=31, width=189, font=self.label_font)
        self.TLabel_Content2.place(relx=0.074, rely=0.66)
        self.TLabel_Content2.configure(anchor='sw')
        self.TLabel_Content2.configure(wraplength=189)
        self.TLabel_Content2.configure(text='''2.输入后点鸡发送，耐心等待服务返回''')

        self.TLabel_Content3 = customtkinter.CTkLabel(self.TFrame1, height=31, width=200, font=self.label_font)
        self.TLabel_Content3.place(relx=0.074, rely=0.74)
        self.TLabel_Content3.configure(anchor='sw')
        self.TLabel_Content3.configure(wraplength=200)
        self.TLabel_Content3.configure(justify='left')
        self.TLabel_Content3.configure(text="3.需要解析文件时，点击上传文件自动上传后生成url再编辑提问内容后点发送（仅gpt4o-all支持文件分析）。")

        self.TLabel_Content4 = customtkinter.CTkLabel(self.TFrame1, height=31, width=200, font=self.label_font)
        self.TLabel_Content4.place(relx=0.074, rely=0.87)
        self.TLabel_Content4.configure(anchor='sw')
        self.TLabel_Content4.configure(wraplength=200)
        self.TLabel_Content4.configure(justify='left')
        self.TLabel_Content4.configure(text="4.因不支持混合提问（图片+文字），图片生成功能会清空对话框，请及时保存。")

        # 中间对话历史
        self.TFrame2 = customtkinter.CTkFrame(self.top)
        self.TFrame2.place(relx=0.235, rely=0.022, relheight=0.967, relwidth=0.165)
        self.TFrame2.configure(border_width=1)

        self.TFrame2Label1 = customtkinter.CTkLabel(self.TFrame2, height=22, width=100, text='''3日内历史对话：''',
                                                    font=self.label_font)
        self.TFrame2Label1.place(relx=0.1, rely=0.028)
        self.TFrame2Label1.configure(anchor='sw')
        # 原生组件
        self.DialogList = tk.Listbox(self.TFrame2)
        self.DialogList.insert(1, "测试对话1")
        self.DialogList.insert(2, "测试对话2")
        self.DialogList.place(relx=0.1, rely=0.098, relwidth=0.8, relheight=0.81)
        # ThemeManager中拉取颜色
        self.DialogList.configure(background=ThemeManager.theme["CTkTextbox"]["fg_color"][1])
        self.DialogList.configure(foreground=ThemeManager.theme["CTkTextbox"]["text_color"][1])
        self.DialogList.configure(highlightcolor=ThemeManager.theme["CTkTextbox"]["border_color"][1])
        self.DialogList.configure(highlightthickness=0)
        self.DialogList.configure(relief="flat")
        self.DialogList.configure(selectmode="SINGLE")
        self.DialogList.configure(selectbackground=ThemeManager.theme["CTkSegmentedButton"]["selected_color"][1])

        self.sbar = ttk.Scrollbar(self.DialogList, command=self.DialogList.yview, style="TFrame")
        self.sbar.pack(side=RIGHT, fill=Y)
        self.DialogList.configure(activestyle="dotbox", yscrollcommand=self.sbar.set)

        # 右下角按钮
        self.TButton_Send = customtkinter.CTkButton(self.top, height=37, width=87, font=self.label_font)
        self.TButton_Send.place(relx=0.817, rely=0.822)
        self.TButton_Send.configure(text='''发送''')
        self.TButton_Send.configure(fg_color="green")
        self.TButton_Send.configure(hover_color="darkgreen")
        self.TButton_Send.configure(command=client_support.send_chat_pre)
        self.TButton_Send.configure(compound='left')
        self.TButton_Send.configure(cursor="boat")

        self.TButton_Upload = customtkinter.CTkButton(self.top, height=37, width=87, font=self.label_font)
        self.TButton_Upload.place(relx=0.817, rely=0.911)
        self.TButton_Upload.configure(command=client_support.upload_file_pre)
        self.TButton_Upload.configure(text='''上传文件''')
        self.TButton_Upload.configure(fg_color="darkviolet")
        self.TButton_Upload.configure(hover_color="indigo")
        self.TButton_Upload.configure(compound='left')
        self.TButton_Upload.configure(cursor="bogosity")

        self.TButton_Refresh = customtkinter.CTkButton(self.top, height=37, width=87, font=self.label_font)
        self.TButton_Refresh.place(relx=0.908, rely=0.822)
        self.TButton_Refresh.configure(text='''刷新对话''')
        self.TButton_Refresh.configure(command=client_support.refresh)
        self.TButton_Refresh.configure(compound='left')
        self.TButton_Refresh.configure(cursor="clock")

        self.TButton_NotSure = customtkinter.CTkButton(self.top, height=37, width=87, font=self.label_font)
        self.TButton_NotSure.place(relx=0.908, rely=0.911)
        self.TButton_NotSure.configure(text='''获取历史对话''')
        self.TButton_NotSure.configure(command=client_support.get_dialog_his)
        self.TButton_NotSure.configure(compound='left')
        self.TButton_NotSure.configure(cursor="man")

        self.result_text = CTkTextbox(self.top, font=self.dialog_font, state="disabled")
        self.result_text.place(relx=0.413, rely=0.022, relheight=0.753, relwidth=0.578)

        # 输入区
        self.TLabel1 = customtkinter.CTkLabel(self.top, text='''请输入发送内容''', height=21, width=51, font=self.label_font)
        self.TLabel1.place(relx=0.413, rely=0.778)
        self.TLabel1.configure()
        self.TLabel1.configure(compound='left')
        # 请求提示
        self.requestHint = customtkinter.CTkLabel(self.top, text='''请求中:''', height=21, width=51, font=self.label_font)
        self.requestHint.configure(compound='left')
        # 进度条
        self.progress = customtkinter.CTkProgressBar(self.top, height=15, width=140)
        self.progress.configure(mode="indeterminate")

        # 输入框
        self.speakBox = CTkTextbox(self.top, font=self.dialog_font)
        self.speakBox.place(relx=0.413, rely=0.822, relheight=0.162, relwidth=0.39)
        self.speakBox.configure(cursor="ibeam")

from time import time


class ToolTip(tk.Toplevel):
    """ Provides a ToolTip widget for Tkinter. """
    def __init__(self, wdgt, msg=None, msgFunc=None, delay=0.5,
                 follow=True):
        self.wdgt = wdgt
        self.parent = self.wdgt.master
        tk.Toplevel.__init__(self, self.parent, bg='black', padx=1, pady=1)
        self.withdraw()
        self.overrideredirect(True)
        self.msgVar = tk.StringVar()
        if msg is None:
            self.msgVar.set('No message provided')
        else:
            self.msgVar.set(msg)
        self.msgFunc = msgFunc
        self.delay = delay
        self.follow = follow
        self.visible = 0
        self.lastMotion = 0
        self.msg = tk.Message(self, textvariable=self.msgVar, bg=_bgcolor,
                   fg=_fgcolor, font="TkDefaultFont",
                   aspect=1000)
        self.msg.grid()
        self.wdgt.bind('<Enter>', self.spawn, '+')
        self.wdgt.bind('<Leave>', self.hide, '+')
        self.wdgt.bind('<Motion>', self.move, '+')
    def spawn(self, event=None):
        self.visible = 1
        self.after(int(self.delay * 1000), self.show)
    def show(self):
        if self.visible == 1 and time() - self.lastMotion > self.delay:
            self.visible = 2
        if self.visible == 2:
            self.deiconify()
    def move(self, event):
        self.lastMotion = time()
        if self.follow is False:
            self.withdraw()
            self.visible = 1
        self.geometry('+%i+%i' % (event.x_root + 20, event.y_root - 10))
        try:
            self.msgVar.set(self.msgFunc())
        except:
            pass
        self.after(int(self.delay * 1000), self.show)
    def hide(self, event=None):
        self.visible = 0
        self.withdraw()
    def update(self, msg):
        self.msgVar.set(msg)
    def configure(self, **kwargs):
        backgroundset = False
        foregroundset = False
        # Get the current tooltip text just in case the user doesn't provide any.
        current_text = self.msgVar.get()
        # to clear the tooltip text, use the .update method
        if 'debug' in kwargs.keys():
            debug = kwargs.pop('debug', False)
            if debug:
                for key, value in kwargs.items():
                    print(f'key: {key} - value: {value}')
        if 'background' in kwargs.keys():
            background = kwargs.pop('background')
            backgroundset = True
        if 'bg' in kwargs.keys():
            background = kwargs.pop('bg')
            backgroundset = True
        if 'foreground' in kwargs.keys():
            foreground = kwargs.pop('foreground')
            foregroundset = True
        if 'fg' in kwargs.keys():
            foreground = kwargs.pop('fg')
            foregroundset = True

        fontd = kwargs.pop('font', None)
        if 'text' in kwargs.keys():
            text = kwargs.pop('text')
            if (text == '') or (text == "\n"):
                text = current_text
            else:
                self.msgVar.set(text)
        reliefd = kwargs.pop('relief', 'flat')
        justifyd = kwargs.pop('justify', 'left')
        padxd = kwargs.pop('padx', 1)
        padyd = kwargs.pop('pady', 1)
        borderwidthd = kwargs.pop('borderwidth', 2)
        wid = self.msg      # The message widget which is the actual tooltip
        if backgroundset:
            wid.config(bg=background)
        if foregroundset:
            wid.config(fg=foreground)
        wid.config(font=fontd)
        wid.config(borderwidth=borderwidthd)
        wid.config(relief=reliefd)
        wid.config(justify=justifyd)
        wid.config(padx=padxd)
        wid.config(pady=padyd)


def start_up():
    client_support.main()

if __name__ == '__main__':
    client_support.main()